baseURL = "https://dung-n-tran.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-black-and-light-theme"

[params]
    sitename = "Dung Tran"
    disableWebFonts = false

[permalinks]
  "/" = "/:filename"
